version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    working_directory: ~/ec2-powercycle
    steps:
      - checkout
      - run:
          name: Change permissions on the file
          command: chmod 755 sh/*.sh

  deploy-master:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/ec2-powercycle
    environment:
      AWS_DEFAULT_REGION: eu-west-1
      AWS_LAMBDA_FUNCTION: ec2-powercycle
      AWS_CROSS_ACCCOUNT_ACCESS_ARN: arn:aws:iam::371548805176:role/circleci-to-ec2powercycle-lambda.infraprod-to-infradev
    steps:
      - checkout
      - run:
          command: |
            ./sh/package.sh
            ./sh/lambda-deploy-latest.sh --file ec2-powercycle.zip
            ./sh/lambda-invoke-function.sh --function ec2-powercycle --dryrun true
            ./sh/iam-assume-role-and-deploy.sh

  deploy-releases:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/ec2-powercycle
    environment:
      AWS_DEFAULT_REGION: eu-west-1
      AWS_LAMBDA_FUNCTION: ec2-powercycle
      AWS_CROSS_ACCCOUNT_ACCESS_ARN: arn:aws:iam::371548805176:role/circleci-to-ec2powercycle-lambda.infraprod-to-infradev
    steps:
      - checkout
      - run:
          command: |
            ./sh/lambda-publish-version.sh
            ./sh/lambda-update-alias.sh --function ec2-powercycle --alias LIVE
            ./sh/iam-assume-role-and-release.sh  --function ec2-powercycle --alias LIVE
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-master:
          context:
            - ec2-powercycle-prod
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-releases:
          context:
            - ec2-powercycle-test
          requires:
            - build
          filters:
            #tags:
            #  only: /release-.*/
            branches:
              only: feature/UPPSF-3187-update-ec-2-powercycle-deploy-jobs-in-circle-ci
              #ignore: /.*/
