version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    working_directory: ~/ec2-powercycle
    steps:
      - checkout
      - run:
          name: Change permissions on the file
          command: chmod 755 sh/*.sh

  deploy-master:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/ec2-powercycle
    environment:
      AWS_DEFAULT_REGION: eu-west-1
      AWS_LAMBDA_FUNCTION: ec2-powercycle
    steps:
      - checkout
      - run:
          command: |
            ./sh/lambda-publish-version.sh
            ./sh/lambda-update-alias.sh --function ec2-powercycle --alias LIVE

  deploy-release:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/ec2-powercycle
    environment:
      AWS_DEFAULT_REGION: eu-west-1
      AWS_LAMBDA_FUNCTION: ec2-powercycle
    steps:
      - checkout
      - run:
          command: |
            ./sh/package.sh
            ./sh/lambda-deploy-latest.sh --file ec2-powercycle.zip
            ./sh/lambda-publish-version.sh
            ./sh/lambda-update-alias.sh --function ec2-powercycle --alias LIVE

  deploy-test:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/ec2-powercycle
    environment:
      AWS_DEFAULT_REGION: eu-west-1
      AWS_LAMBDA_FUNCTION: ec2-powercycle
    steps:
      - checkout
      - run:
          command: |
            ./sh/package.sh
            ./sh/lambda-deploy-latest.sh --file ec2-powercycle.zip
            ./sh/lambda-invoke-function.sh --function ec2-powercycle --dryrun true

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-test:
          context:
            - ec2-powercycle-test
          requires:
            - build
          filters:
            branches:
              ignore: master
      - deploy-master:
          context:
            - ec2-powercycle-test
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-release:
          context:
            - ec2-powercycle-test
          filters:
            tags:
              only: /test-.*/
            branches:
              ignore: /.*/
